apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: ${{values.namespace | dump}}
    backstage.io/kubernetes-id: ${{values.component_id | dump}}
    janus-idp.io/tekton : ${{values.component_id | dump}}
    backstage.io/kubernetes-label-selector: 'app=${{values.component_id | dump}}'
  links:
    - title: Documentation
      url: https://github.com/maximilianoPizarro/moodle/blob/main/README.md 
    - url: https://workspaces.openshift.com/#https://github.com/maximilianopizarro/moodle
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://moodle-maximilianopizar-2-dev.apps.rm2.thpm.p1.openshiftapps.com
      title: Moodle Url
      icon: web
  tags:
    - template
    - tekton
    - moodle
    - dev      
spec:
  type: webside
  lifecycle: experimental
  owner: ${{values.owner | dump}}
