apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  description: "Moodle for Red Hat Developer Hub"
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: ${{values.namespace | dump}}
    backstage.io/kubernetes-id: ${{values.component_id | dump}}
    janus-idp.io/tekton : ${{values.component_id | dump}}
    backstage.io/kubernetes-label-selector:  app=${{values.component_id | dump}}
  links:
    - title: Documentation
      url: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}/blob/main/README.md 
    - url: https://workspaces.openshift.com/#${{values.destination.owner + "/" + values.destination.repo}}/moodle
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://${{values.component_id | dump}}-maximilianopizar-2-dev.apps.rm2.thpm.p1.openshiftapps.com
      title: Moodle Url
      icon: web
  tags:
    - template
    - tekton
    - moodle
    - dev      
spec:
  type: webside
  lifecycle: experimental
  owner: ${{values.owner | dump}}
