apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: moodle-template
  title: Moodle Software Template
  description: Plantilla para configurar un pipeline de Tekton para Moodle
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: moodle
    backstage.io/tekton-enabled: "true"
spec:
  owner: group:default/maximilianopizarro
  type: service
  parameters:
    - title: Información del Pipeline
      required:
        - appName
        - gitRepo
        - gitRevision
        - imageName
        - pathContext
        - version
        - externalUrl
        - orgName
        - namespace
      properties:
        appName:
          title: Nombre de la Aplicación
          type: string
          description: Nombre de la aplicación Moodle
          default: moodle
        gitRepo:
          title: Repositorio Git
          type: string
          description: URL del repositorio de código fuente
          default: https://github.com/moodle/moodle
        gitRevision:
          title: Revisión Git
          type: string
          description: Rama o tag de Git a utilizar
          default: MOODLE_311_STABLE
        imageName:
          title: Nombre de la Imagen
          type: string
          description: Ruta de la imagen en el registro
          default: image-registry.openshift-image-registry.svc:5000/maximilianopizar-2-dev/moodle
        pathContext:
          title: Contexto de Build
          type: string
          description: Ruta del contexto para la construcción de la imagen
          default: .
        version:
          title: Versión
          type: string
          description: Versión de PHP a utilizar
          default: maximilianopizar-2-dev/php-74
        externalUrl:
          title: URL Externa
          type: string
          description: URL externa para acceder a la aplicación Moodle
          default: moodle-maximilianopizar-2-dev.apps.rm2.thpm.p1.openshiftapps.com
        orgName:
          title: Nombre de la Organización GitHub
          type: string
          description: Nombre de la organización para los repositorios
          default: maximilianoPizarro
        namespace:
          title: Namespace Kubernetes
          type: string
          description: Namespace donde se ejecutará el pipeline
          default: default
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./
        values:
          component_id: ${{ parameters.appName }}
          description:  ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}
          # cluster: {{ cluster_subdomain }}
          host: ${{ parameters.repo.host }}
          destination_own: ${{ parameters.repo.owner }}          
    - id: create-gitops-repo
      name: Crear Repositorio GitOps
      action: publish:github
      input:
        allowedHosts:
          - github.com      
        repoUrl: ${{ parameters.repoUrl }}
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.create-gitops-repo.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
  output:
    links:
      - title: Repository
        url: ${{ steps.create-gitops-repo.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}