kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: php-74-moodle
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'php-74:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'registry.redhat.io/ubi8/php-74:latest'
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: "FROM registry.redhat.io/ubi8/php-74:latest\r\nUSER root\r\n\r\nENV DOCUMENT_ROOT=/opt/app-root/src\r\n\r\nRUN dnf install php-xmlrpc php-zip -y\r\n\r\nRUN chown 1001:0 $DOCUMENT_ROOT && chgrp -R 0 $DOCUMENT_ROOT && chmod -R g=u $DOCUMENT_ROOT\r\n\r\nUSER 1001"
  runPolicy: Serial
