kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: moodle
spec:
  lookupPolicy:
    local: false
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: php-74
spec:
  lookupPolicy:
    local: false

