---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./pvc.yaml
- ./buildconfig.yaml
- ./configmap.yaml
- ./pvc.yaml
- ./deployment.yaml
- ./service.yaml
- ./imagestream.yaml
