apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-data
  labels:
    app.kubernetes.io/instance: moodle
    app.kubernetes.io/name: moodle
    app.kubernetes.io/part-of: moodle      
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: posgre
  labels:
    app.kubernetes.io/instance: moodle
    app.kubernetes.io/name: moodle
    app.kubernetes.io/part-of: moodle      
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
